### ISSUE TITLE
bootstrapping vm fails

### ISSUE THREAD

**Issue by akarasulu** [debops/examples#16]
Trying to bootstrap a VM in multi VM environment:

```shell
$ ANSIBLE_SSH_ARGS="-o UserKnownHostsFile=/dev/null" debops boostrap -l h1 -u root -k
Running Ansible playbooks:
/usr/local/lib/python3.8/site-packages/debops/ansible/playbooks/site.yml
ERROR! the playbook: boostrap could not be found
```

On a mac with brew installed ansible, debops via pip. Any ideas?

**Comment by akarasulu** [comment]
Incidentally, I checked for the presence of the bootstrap.yml and its present under  `/usr/local/lib/python3.8/site-packages/debops/ansible/playbooks/bootstrap.yml`. Maybe this is a brew ansible / pip debops thing but I don't have this problem otherwise.

Also the example simpletest.yml runs without issue. Just cannot perform normal debops runs with this setup.

Thanks in advance for your help.

**Comment by nqb** [comment]
`bootstrap` in place of `boostrap` ? (with a `t`)

**Comment by akarasulu** [comment]
You know I feel like an idiot ... so sorry about bothering you. Thank you.

**Comment by nqb** [comment]
You're welcome ;-)
