### ISSUE TITLE
vagrant-multi-machine

### ISSUE THREAD

**Issue by MatthewMi11er** [debops/examples#7]
To simplify the Ansible/Vagrant issue I created a [basic provisioner](https://github.com/MatthewMi11er/vai) which outputs the vagrant file to wherever you like. You can then run Ansible or Debops outside of Vagrant as normal. Using a custom provisioner means you don't need to create a dummy playbook, vagrant won't try to run Ansible at all and you can specify where you want the inventory to be created, so you don't have to use symlinks. It also means you don't have to deal with port numbers and ssh keys like you would with a hand-crafted inventory file.

I haven't yet fixed the issue of it running for each machine defined in the Vagrantfile , but doing so doesn't hurt anything and is easy to work around.

**Comment by drybjed** [comment]
@MatthewMi11er Good to know! I'm really using Vagrant myself, preferring straight `libvirt` + KVM, but I'm sure some of my users will be interested.

**Comment by htgoebel** [comment]
This seams to be really great! I'm going to update the example soon.

**Comment by htgoebel** [comment]
Solved by #8 resp. e84c95075e0cf79fae5ca36ff2bba5321ac9c7d9
